[package]
name = "elegua_parser"
version = "0.0.1"
authors = ["kHigasa <kojihigasa@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
lalrpop-util = "0.16.3"
log="0.4.1"
regex="0.2.2"
num-bigint = "0.2"
num-traits = "0.2"

